-- Contagem própria de acessos para o painel Dev. O navegador recebe um UUID
-- aleatório persistido em localStorage; não guardamos IP nem fingerprint.

create table if not exists public.site_devices (
  id uuid primary key,
  device_type text not null check (device_type in ('desktop', 'mobile', 'tablet', 'other')),
  browser text not null check (char_length(browser) between 1 and 80),
  os text not null check (char_length(os) between 1 and 80),
  is_owner boolean not null default false,
  owner_label text check (owner_label is null or char_length(owner_label) between 1 and 80),
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  last_path text check (last_path is null or char_length(last_path) <= 500)
);

create table if not exists public.site_access_events (
  id bigint generated by default as identity primary key,
  device_id uuid not null references public.site_devices(id) on delete cascade,
  path text not null check (char_length(path) between 1 and 500),
  user_id uuid references auth.users(id) on delete set null,
  visited_at timestamptz not null default now()
);

create index if not exists site_devices_last_seen_idx
  on public.site_devices (last_seen_at desc);

create index if not exists site_access_events_visited_at_idx
  on public.site_access_events (visited_at desc);

create index if not exists site_access_events_device_visited_idx
  on public.site_access_events (device_id, visited_at desc);

alter table public.site_devices enable row level security;
alter table public.site_access_events enable row level security;

drop policy if exists "site_devices_select_admin" on public.site_devices;
create policy "site_devices_select_admin" on public.site_devices
  for select to authenticated
  using ((select public.auth_user_role()) = 'admin');

drop policy if exists "site_access_events_select_admin" on public.site_access_events;
create policy "site_access_events_select_admin" on public.site_access_events
  for select to authenticated
  using ((select public.auth_user_role()) = 'admin');

-- Não há INSERT/UPDATE público: a rota do servidor valida o payload e usa a
-- service role. O grant abaixo serve apenas para a leitura protegida por RLS.
revoke all on table public.site_devices from anon, authenticated;
revoke all on table public.site_access_events from anon, authenticated;
grant select on table public.site_devices to authenticated;
grant select on table public.site_access_events to authenticated;

-- A migration 060 já criava as políticas desta tabela, mas o advisor apontou
-- que o RLS estava desativado no banco de produção. Reafirma a proteção sem
-- alterar as policies nem o fluxo do app Android.
alter table public.admin_fcm_tokens enable row level security;
